"""Topic tagging with a local MLX model.

The tag is one general category plus one or two specific subjects, generated by
asking for JSON and parsing it. That shape was arrived at empirically:

- "Summarize" framing does not work with models this size. Dicta 1.7B and
  Qwen3-4B both ignore length instructions under it and produce full
  explanatory sentences or markdown bullet lists. "Topic tag" framing keeps
  them terse. English output is also markedly more verbose than Hebrew for the
  same model. The index exists to be scanned, so short wins.
- A single generic tag ("tech meeting") was too vague to pick a call out of a
  list, hence general + specific rather than a longer field.
- JSON either parses or fails obviously, where free text can silently yield a
  mangled tag. The fallback below handles the models that ignore the JSON
  instruction anyway.

`mlx_lm` is imported lazily, inside the load call: it takes seconds to import,
and no other subcommand should pay that just to read the index.
"""

from __future__ import annotations

import json
import re
from typing import Any

from .config import Config
from .sidecar import Tag

JSON_SYSTEM_HE = (
    "אתה מייצר תגיות נושא קצרות לתמלולי שיחות. "
    'ענה אך ורק באובייקט JSON בצורה {"general": "...", "specific": ["...", "..."]}. '
    "general היא 1-2 מילים בלבד שמתארות את סוג השיחה "
    "(לדוגמה: פגישת צוות, דיבוג, סנכרון). "
    "specific היא רשימה של תגית אחת או שתיים בדיוק "
    "(לא יותר!, 2-4 מילים כל אחת) על הנושאים "
    "המרכזיים ביותר שנדונו, מבוסס אך ורק על התמלול. כל שדה חייב להיות קצר. "
    "בלי markdown, בלי טקסט נוסף, רק ה-JSON עצמו."
)
JSON_SYSTEM_EN = (
    "You generate short topic tags for call transcripts. "
    "Respond with ONLY a JSON object of the form "
    '{"general": "...", "specific": ["...", "..."]}. '
    "general is 1-2 words describing the call type "
    "(e.g. team meeting, debugging, sync). "
    "specific is a list of exactly one or two short phrases "
    "(no more!, 2-4 words each) naming the "
    "main subjects discussed, based only on the transcript. Every field must be short. "
    "No markdown, no extra text, just the JSON."
)

# Used when the model ignores the JSON instruction (observed on long, dense
# transcripts with a 1.7B model): ask for a single plain tag instead, then pull
# it out of whatever the model wrote via label matching.
FALLBACK_SYSTEM_HE = "תן תגית נושא קצרה לשיחה הבאה (עד 5 מילים, לא משפט, בלי הסברים)."
FALLBACK_SYSTEM_EN = (
    "Give a short topic tag for the following call transcript "
    "(up to 5 words, not a sentence, no explanations)."
)

# The model sometimes answers in the "wrong" language for the fallback case, so
# both label sets are always checked regardless of the requested language.
LABEL_WORDS = (
    "topic tag",
    "topic",
    "tag",
    "תגית נושא",
    "נושא השיחה",
    "נושא",
    "תגית",
)

MAX_GENERAL_WORDS = 3
MAX_SPECIFIC_WORDS = 5
MAX_SPECIFIC_TAGS = 2
MAX_FALLBACK_WORDS = 10


class TopicError(Exception):
    """The model could not be loaded, or produced nothing usable."""


def cap_words(text: str, max_words: int) -> str:
    return " ".join(text.split()[:max_words]).rstrip(",.;:")


def parse_json_tag(text: str) -> Tag | None:
    stripped = re.sub(
        r"^```(?:json)?|```$", "", text.strip(), flags=re.MULTILINE
    ).strip()
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None

    general = cap_words(str(data.get("general", "")).strip(), MAX_GENERAL_WORDS)
    specific_raw = data.get("specific", [])
    if not isinstance(specific_raw, list):
        specific_raw = [specific_raw]
    specific = [
        cap_words(str(item).strip(), MAX_SPECIFIC_WORDS)
        for item in specific_raw
        if str(item).strip()
    ][:MAX_SPECIFIC_TAGS]

    if not general and not specific:
        return None
    return Tag(general=general, specific=specific)


def extract_plain_tag(text: str) -> str:
    label_pattern = "|".join(re.escape(word) for word in LABEL_WORDS)
    labeled = re.compile(rf"^(?:{label_pattern})\s*:\s*(.+)$", re.IGNORECASE)
    for raw_line in text.splitlines():
        line = re.sub(r"\*+", "", raw_line).strip()
        match = labeled.match(line)
        if match:
            candidate = match.group(1).strip("'\" ")
            if candidate:
                return cap_words(candidate, MAX_FALLBACK_WORDS)

    # Models that ignore the "short tag" instruction on long transcripts tend
    # to answer with a markdown bullet list instead (observed on long,
    # technical group calls with a 1.7B model). The bold label in the first
    # actual bullet (not a bare "**Section:**" header line) is usually a good
    # short topic on its own, and better than the intro sentence below.
    bullet = re.compile(r"^[*\-]\s+\*\*(.+?)\*\*")
    for raw_line in text.splitlines():
        match = bullet.match(raw_line.strip())
        if match:
            candidate = match.group(1).strip().rstrip(":").strip()
            if candidate:
                return cap_words(candidate, MAX_FALLBACK_WORDS)

    for raw_line in text.splitlines():
        line = re.sub(r"\*+", "", raw_line).strip().strip("'\" ")
        if line:
            return cap_words(line, MAX_FALLBACK_WORDS)
    return ""


class Tagger:
    """A loaded model, reused across every transcript in one run."""

    def __init__(self, model: Any, tokenizer: Any, model_path: str, config: Config):
        self.model = model
        self.tokenizer = tokenizer
        self.model_path = model_path
        self.config = config

    @classmethod
    def load(cls, config: Config, lang: str, model_path: str | None = None) -> Tagger:
        path = model_path or config.model_for_lang(lang)
        try:
            from mlx_lm import load
        except ImportError as exc:  # pragma: no cover - environment problem
            raise TopicError(f"mlx-lm is not available: {exc}") from exc
        try:
            # load() is typed as returning either (model, tokenizer) or
            # (model, tokenizer, config) - the third only with
            # return_config=True, which we never pass. Index rather than
            # unpack so the declared union doesn't have to be narrowed.
            loaded = load(path)
            model, tokenizer = loaded[0], loaded[1]
        except Exception as exc:
            # mlx_lm/huggingface_hub raise a mix of exception types for a bad
            # path or repo; surface one clean error instead of a traceback.
            raise TopicError(f"failed to load model {path}: {exc}") from exc
        return cls(model, tokenizer, path, config)

    def _prompt(self, system: str, transcript: str, label: str) -> str:
        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": f"{label}:\n{transcript}"},
        ]
        # enable_thinking=False matters for Qwen3: as a reasoning model it
        # otherwise burns the whole token budget on a <think> preamble before
        # ever emitting the tag.
        return self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=False,
        )

    def _generate(self, prompt: str) -> str:
        from mlx_lm import generate

        return generate(
            self.model,
            self.tokenizer,
            prompt=prompt,
            max_tokens=self.config.max_tokens,
            verbose=False,
        )

    def tag(self, transcript: str, lang: str) -> Tag:
        label = "שיחה" if lang == "he" else "Transcript"

        json_system = JSON_SYSTEM_HE if lang == "he" else JSON_SYSTEM_EN
        text = self._generate(self._prompt(json_system, transcript, label))
        tag = parse_json_tag(text)
        if tag is not None:
            return tag

        fallback_system = FALLBACK_SYSTEM_HE if lang == "he" else FALLBACK_SYSTEM_EN
        text = self._generate(self._prompt(fallback_system, transcript, label))
        return Tag(general=extract_plain_tag(text))
